### ISSUE TITLE
Test fails, but gitarro returns 0

### ISSUE THREAD

**Issue by juliogonzalez** [openSUSE/gitarro#116]
https://ci.suse.de/job/manager-prs-schema-migration-pipeline/25265/

I'd say this is provoking the failure:
```
[Run tests oracle] *** Progress: #
[Run tests oracle] Could not populate database.
```
Shouldn't gitarro produce a log line to inform that the test is failed?

And of course, it should return != 0 so the CI job fails.

**Comment by juliogonzalez** [comment]
Fixed.

**Comment by mcalmer** [comment]
I have currently trouble with gitarro cannot rerun a test. The test just abort  with an error i do not understand.

https://github.com/uyuni-project/uyuni/pull/152

Check the ci logs

**Comment by juliogonzalez** [comment]
@mcalmer, I guess you are talking about the last error:
```
hudson.AbortException: No test report files were found. Configuration error?
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:154)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:118)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3084)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at hudson.remoting.Engine$1$$Lambda$4.0000000054014720.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:811)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from sumadocker4.mgr.suse.de/10.162.210.20:35428
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1070)
		at hudson.FilePath.act(FilePath.java:1059)
		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114)
		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137)
		at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167)
		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:50)
		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:23)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
		at java.util.concurrent.FutureTask.run(FutureTask.java:277)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		... 1 more
```
That's a problem with the pipeline for that job, as it seems no test report are found when test unit are failing. I guess we need an issue at SUSE/susemanager-ci so this is handled propperly instead of just producing a stacktrace.

But if you go to the build information: https://ci.suse.de/job/Uyuni-PRs/job/Uyuni-PRs-pgsql-pipeline/10876/

You will noticed that it points you to failed tests and testcases:

```
   [junit] Testsuite: com.redhat.rhn.domain.kickstart.test.CancelKickstartTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.034 sec
    [junit] 
    [junit] Testcase: testCanceledActions(com.redhat.rhn.domain.kickstart.test.CancelKickstartTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.redhat.rhn.manager.kickstart.test.KickstartScheduleCommandTest.testCommandExecution(KickstartScheduleCommandTest.java:348)
    [junit] 	at com.redhat.rhn.manager.kickstart.test.KickstartScheduleCommandTest.scheduleAKickstart(KickstartScheduleCommandTest.java:313)
    [junit] 	at com.redhat.rhn.domain.kickstart.test.CancelKickstartTest.testCanceledActions(CancelKickstartTest.java:45)
    [junit] 
    [junit] 
    [junit] TEST com.redhat.rhn.domain.kickstart.test.CancelKickstartTest FAILED
```
```
 [junit] Testsuite: com.redhat.rhn.frontend.action.kickstart.test.KickstartPartitionActionTest
    [junit] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.955 sec
    [junit] 
    [junit] Testcase: testCleanSubmit(com.redhat.rhn.frontend.action.kickstart.test.KickstartPartitionActionTest):	FAILED
    [junit] was expecting 2 action message(s), but received 1 action message(s)
    [junit] junit.framework.AssertionFailedError: was expecting 2 action message(s), but received 1 action message(s)
    [junit] 	at servletunit.struts.Common.verifyActionMessages(Common.java:93)
    [junit] 	at servletunit.struts.MockStrutsTestCase.verifyActionMessages(MockStrutsTestCase.java:835)
    [junit] 	at com.redhat.rhn.frontend.action.kickstart.test.KickstartPartitionActionTest.testCleanSubmit(KickstartPartitionActionTest.java:69)
    [junit] 
    [junit] 
    [junit] Testcase: testMultipleSwapsSubmit(com.redhat.rhn.frontend.action.kickstart.test.KickstartPartitionActionTest):	FAILED
    [junit] was expecting 2 action message(s), but received 1 action message(s)
    [junit] junit.framework.AssertionFailedError: was expecting 2 action message(s), but received 1 action message(s)
    [junit] 	at servletunit.struts.Common.verifyActionMessages(Common.java:93)
    [junit] 	at servletunit.struts.MockStrutsTestCase.verifyActionMessages(MockStrutsTestCase.java:835)
    [junit] 	at com.redhat.rhn.frontend.action.kickstart.test.KickstartPartitionActionTest.testMultipleSwapsSubmit(KickstartPartitionActionTest.java:95)
    [junit] 
    [junit] 
```
Besides, the fix for this issue is not even released as a Gem, so the CI is not using it yet.

**Comment by mcalmer** [comment]
@juliogonzalez I run these tests in eclipse and they were sucessful. So i wanted to rerun them. But this result directly in the first error before the test even started.

So yes, the backtrace may hapoen because there are no test results, but my problem is that the tests never really started.
